# 1. Basic Linear Algebra

* [1.1 Creating tensors](#creating_tensors)
* [1.2 Scalars](#Scalars)
* [1.3 Vectors](#Vectors)
* [1.4 Matrices](#Matrices)
* [1.5 Basic Properties of Tensor Arithmetic](#Basic_Properties_of_Tensor_Arithmetic)
* [1.6 Reduction](#Reduction)

In [3]:
# Check for tensorflow version
import tensorflow as tf
print(tf.__version__)

2.9.1


In [15]:
import numpy as np

<a id = "creating_tensors"> </a>

### 1. 1 Creating tensors

In this section, we will create `tensors` of different rank, starting from scalars to multi-dimensional arrays. Though tensors can be both real or complex, we will mainly focus on real tensors.

A scalar contains a single (real or complex) value. 

In [17]:
a = tf.constant(50.0)
a

<tf.Tensor: shape=(), dtype=float32, numpy=50.0>

In [25]:
print(a)

tf.Tensor(50.0, shape=(), dtype=float32)


In [19]:
print(a.numpy())

50.0


<a id = "Scalars"> </a>
## 1. 2 Scalars

![alt](1Scalars.png)

In [20]:

x = tf.constant(30.0)
y = tf.constant(20.0)

x + y, x * y, x / y, x**y

(<tf.Tensor: shape=(), dtype=float32, numpy=50.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=600.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.5>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.4867842e+29>)

In [21]:
print(x)  # its tensor

tf.Tensor(30.0, shape=(), dtype=float32)


In [22]:
type(x)

tensorflow.python.framework.ops.EagerTensor

In [27]:
 val = x + y

In [28]:
type(val)

tensorflow.python.framework.ops.EagerTensor

In [29]:
print(val)

tf.Tensor(50.0, shape=(), dtype=float32)


In [30]:
print(val.numpy())

50.0


<a id = "Vectors"> </a>
## 1.3  Vectors
Vectors are implemented as 
`1st`-order tensors. In general, such tensors can have arbitrary lengths, subject to memory limitations. Caution: in Python, like in most programming languages, vector indices start at 
, also known as `0` zero-based indexing, whereas in linear algebra subscripts begin at 
 `1` (one-based indexing).

In [35]:
x = tf.range(7)
x

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6])>

In [36]:
x

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6])>

We can refer to an element of a vector by using a subscript. For example, `x2`
 denotes the second element of `x`
. Since `x2`
 is a scalar, we do not bold it. By default, we visualize vectors by stacking their elements vertically.
![alt](oneDvector.png)
Here `x1,.....,xn`
 are elements of the vector. Later on, we will distinguish between such column vectors and row vectors whose elements are stacked horizontally. Recall that we access a tensor’s elements via indexing.

In [134]:
type(x)

tensorflow.python.framework.ops.EagerTensor

In [135]:
print(x)

tf.Tensor([ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.], shape=(11,), dtype=float32)


In [136]:
print(x.numpy()) # we can think of it as a vector

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [137]:
x[0].numpy()

0.0

<a id = "Matrics"> </a>
## 1.4 Matrics

![alt](Matrix2.png)

In [47]:
A = tf.reshape(tf.range(6), (3, 2))
A

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3],
       [4, 5]])>

In [48]:
print(A.numpy())

[[0 1]
 [2 3]
 [4 5]]


In [49]:
A.numpy()

array([[0, 1],
       [2, 3],
       [4, 5]])

In [50]:
type(A)

tensorflow.python.framework.ops.EagerTensor

![alt](Matrix1.png)

we can perform this transpose operation simply use of `tf.transpose()`

In [52]:
tf.transpose(A)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 2, 4],
       [1, 3, 5]])>

![alt](Matrix3.png)

In [56]:
A = tf.constant([[16, 20, 30], [28, 8, 40], [30, 40, 50]])
print(A.numpy())

[[16 20 30]
 [28  8 40]
 [30 40 50]]


In [57]:
A == tf.transpose(A) # we can see the equality of the matrix

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])>

<a id = "Basic Properties of Tensor Arithmetic"> </a>
### 1.5 Basic Properties of Tensor Arithmetic

In [59]:
A = tf.reshape(tf.range(6, dtype=tf.float32), (2, 3))

In [62]:
A.numpy()

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [63]:
B = A  # No cloning of `A` to `B` by allocating new memory

In [64]:
B.numpy()

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [66]:
 A + B

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.]], dtype=float32)>

### Hadamard Product

![alt](matrix4.png)

![alt](matrix5.png)

In [67]:
A * B

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.,  1.,  4.],
       [ 9., 16., 25.]], dtype=float32)>

Adding or multiplying a scalar and a tensor produces a result with the same shape as the original tensor. Here, each element of the tensor is added to (or multiplied by) the scalar.

In [69]:
a = 20
X = tf.reshape(tf.range(24), (2, 3, 4))
a + X, (a * X).shape

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],
 
        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43]]])>,
 TensorShape([2, 3, 4]))

<a id = "Reduction"> </a>
# Reduction

![alt](reduction1.png)

In [77]:
x = tf.range(11, dtype=tf.float32)


In [78]:
x.numpy()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
      dtype=float32)

In [79]:
tf.reduce_sum(x).numpy()

55.0

In [80]:
print(x.numpy())

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


![alt](reduction2.png)

In [116]:
M = tf.reshape(tf.range(36, dtype=tf.float32), (4, 9))
print(M.numpy())

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23. 24. 25. 26.]
 [27. 28. 29. 30. 31. 32. 33. 34. 35.]]


In [126]:
M[0].numpy()

array([0., 1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

In [127]:
M[1].numpy()

array([ 9., 10., 11., 12., 13., 14., 15., 16., 17.], dtype=float32)

In [117]:
M.shape

TensorShape([4, 9])

In [118]:
tf.reduce_sum(M)

<tf.Tensor: shape=(), dtype=float32, numpy=630.0>

In [119]:
tf.reduce_sum(M).numpy()

630.0

To sum over all elements along the rows (axis 0), we specify axis=0 in sum. Since the input matrix reduces along axis 0 to generate the output vector, this axis is missing from the shape of the output.

In [120]:
tf.reduce_sum(M, axis=0).numpy() # axis = 0 means row wise operation

array([54., 58., 62., 66., 70., 74., 78., 82., 86.], dtype=float32)

Specifying axis=1 will reduce the column dimension (axis 1) by summing up elements of all the columns.

In [121]:
tf.reduce_sum(M, axis=1).numpy() # axis = 1 column wise operation

array([ 36., 117., 198., 279.], dtype=float32)

In [122]:
tf.reduce_sum(M, axis=0).shape

TensorShape([9])

In [123]:
tf.reduce_sum(M, axis=1).shape

TensorShape([4])

In [124]:
tf.reduce_sum(M, axis=[0, 1]), tf.reduce_sum(M) # Same as `tf.reduce_sum(M)`

(<tf.Tensor: shape=(), dtype=float32, numpy=630.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=630.0>)

A related quantity is the mean, also called the average. We calculate the mean by dividing the sum by the total number of elements. Because computing the mean is so common, it gets a dedicated library function that works analogously to sum.

In [128]:
tf.reduce_mean(M).numpy()

17.5

In [129]:
avg = tf.reduce_sum(M) / tf.size(M).numpy()

In [130]:
avg.numpy()

17.5

In [133]:
tf.reduce_mean(A, axis=0).numpy()

array([1.5, 2.5, 3.5], dtype=float32)

In [138]:
tf.reduce_sum(A, axis=0) / A.shape[0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.5, 2.5, 3.5], dtype=float32)>

### Thank You

“You have to grow from the inside out. None can teach you,
none can make you spiritual.
There is no other teacher but your own soul.”
― Swami Vivekananda